Hosts/FilmLens.MVC/Models/MovieViewModel.cs
using FilmLens.Contracts.Genres;
using FilmLens.Contracts.Movies;
using FilmLens.Contracts.Reviews;

namespace FilmLens.MVC.Models
{
	/// <summary>
	/// Модель фильма.
	/// </summary>
	public class MovieViewModel
	{
		public ReviewViewModel Review { get; set; }

		public MovieDto Movie { get; set; }

		/// <summary>
		/// Флаг для проверки, в избранном ли фильм.
		/// </summary>
		public bool IsFavorite { get; set; }

		public List<GenreDto> Genres { get; set; }

		public List<ReviewDto> Reviews { get; set; }
	}
}

Hosts/FilmLens.MVC/Controllers/GenreController.cs
using FilmLens.AppServices.Genres.Repositories;
using FilmLens.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLens.MVC.Controllers
{
	public class GenreController : Controller
	{
		private readonly IGenreRepository _genreRepository;

        public GenreController(IGenreRepository genreRepository)
        {
            _genreRepository = genreRepository;
        }

		/// <summary>
		/// Заполняет данными страницу с жанрами.
		/// </summary>
		/// <param name="cancellationToken">Токен отмены операции.</param>
		public async Task<IActionResult> GenresPage(CancellationToken cancellationToken)
		{
			var genres = await _genreRepository.GetAllGenresAsync(cancellationToken);

			var viewModel = new GenresViewModel
			{ 
				Genres = genres 
			};
			return View(viewModel);
		}
	}
}

Hosts/FilmLens.MVC/Controllers/MovieController.cs
using AutoMapper;
using FilmLens.AppServices.Common.TMDb;
using FilmLens.AppServices.FavoriteMovies.Repositories;
using FilmLens.AppServices.Genres.Services;
using FilmLens.AppServices.Movies.Repositories;
using FilmLens.AppServices.Movies.Services;
using FilmLens.AppServices.Reviews.Services;
using FilmLens.AppServices.Users.Services;
using FilmLens.Contracts.Common;
using FilmLens.Contracts.Movies;
using FilmLens.Domain.Entities;
using FilmLens.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLens.MVC.Controllers
{
	public class MovieController : Controller
	{
		private readonly IMovieService _movieService;
		private readonly IUserService _userService;
		private readonly IMovieRepository _movieRepository;
		private readonly IFavoriteMovieRepository _favoriteMovieRepository;
		private readonly IGenreService _genreService;
		private readonly IReviewService _reviewService;
		private readonly ITmdbService _tmdbService;
		private readonly IMapper _mapper;

		public MovieController(IMovieService movieService,
							   IMovieRepository movieRepository,
							   IFavoriteMovieRepository favoriteMovieRepository,
							   IUserService userService,
							   IGenreService genreService,
							   IReviewService reviewService,
							   ITmdbService tmdbService, 
							   IMapper mapper)
        {
            _movieService = movieService;
			_movieRepository = movieRepository;
			_favoriteMovieRepository = favoriteMovieRepository;
			_userService = userService;
			_genreService = genreService;
			_reviewService = reviewService;
            _tmdbService = tmdbService;
			_mapper = mapper;
        }

		/// <summary>
		/// Создает фильм.
		/// </summary>
		/// <param name="TmdbId">Идентификатор фильма в TMDb.</param>
		/// <param name="returnUrl">Путь к странице.</param>
		/// <param name="cancellationToken">Токен отмены операции.</param>
        [HttpPost]
        public async Task<IActionResult> AddMovie(int TmdbId, string returnUrl, CancellationToken cancellationToken)
        {
			var existingMovies = await _movieService.GetMoviesAsync(new PagedRequest
            { PageNumber = 1, PageSize = int.MaxValue }, cancellationToken);

			if (existingMovies.Result.Any(m => m.TmdbId == TmdbId.ToString()))
			{
				TempData["ModalMessage"] = "Фильм уже существует в базе данных.";
				return Redirect(returnUrl);
			}

			var tmdbMovie = await _tmdbService.GetMovieDetails(TmdbId);

			if (tmdbMovie == null)
			{
				TempData["ModalMessage"] = "Фильм с указанным ID не найден в TMDb API.";
				return Redirect(returnUrl);
			}

			var movieDto = _mapper.Map<MovieDto>(tmdbMovie);

			await _movieService.AddMovieAsync(movieDto, cancellationToken);

			TempData["SuccessMessage"] = "Фильм успешно добавлен.";
			return Redirect(returnUrl);
		}

		/// <summary>
		/// Удаляет фильм.
		/// </summary>
		/// <param name="movieId">Идентификатор фильма.</param>
		/// <param name="returnUrl">Путь к странице.</param>
		/// <param name="cancellationToken">Токен отмены операции.</param>
		public async Task<IActionResult> RemoveMovie(int movieId, string returnUrl, CancellationToken cancellationToken)
		{
			var movieDto = await _movieService.GetMovieAsync(movieId, cancellationToken);

			if (movieDto == null)
			{
				TempData["ModalMessage"] = "Фильм с указанным ID не найден.";
				return Redirect(returnUrl);
			}

			var movie = _mapper.Map<Movie>(movieDto);

			await _movieRepository.DeleteAsync(movie, cancellationToken);

			TempData["SuccessMessage"] = "Фильм успешно удален.";
			return Redirect(returnUrl);
		}

		/// <summary>
		/// Заполняет данными пагинируемую страницу с фильмами.
		/// </summary>
		/// <param name="pageNumber">Номер страницы (параметр для пагинации).</param>
		/// <param name="genreId">Идентификатор жанра.</param>
		/// <param name="userId">Идентификатор пользователя.</param>
		/// <param name="genreName">Наименование жанра.</param>
		/// <param name="cancellationToken">Токен отмены операции.</param>
		public async Task<IActionResult> MoviesPage(int pageNumber = 1, int? genreId = null, int? userId = null, string? genreName = null, CancellationToken cancellationToken = default)
		{
			var result = await _movieService.GetMoviesAsync(new PagedRequest
			{ 
				PageNumber = pageNumber,
				PageSize = 15, 
				GenreId = genreId,
				GenreName = genreName,
				UserId = userId
			}, cancellationToken);

			return View(result);
		}

		/// <summary>
		/// Заполняет данными страницу с фильмом.
		/// </summary>
		/// <param name="id">Идентификатор фильма.</param>
		/// <param name="cancellationToken">Токен отмены операции.</param>
		public async Task<IActionResult> MoviePage(int id, CancellationToken cancellationToken)
		{
			var isFavorite = false;
			var user = await _userService.GetUserAsync(User);
			var movie = await _movieService.GetMovieAsync(id, cancellationToken);
			var genres = await _genreService.GetGenresAsync(id, cancellationToken);
			var reviews = await _reviewService.GetMovieReviewsAsync(id, cancellationToken);

			if(user != null)
			{
				isFavorite = await _favoriteMovieRepository.ExistsAsync(user.Id, movie.Id);
			}
			
			var result = new MovieViewModel 
			{
				Movie = movie,
				Genres = genres,
				Reviews = reviews,
				IsFavorite = isFavorite
			};

			return View(result);
		}

		/// <summary>
		/// Добавляет фильм в избранное.
		/// </summary>
		/// <param name="movieId">Идентификатор фильма.</param>
		/// <param name="cancellationToken">Токен отмены операции.</param>
		public async Task<IActionResult> AddToFavorites(int movieId, CancellationToken cancellationToken)
		{
			var user = await _userService.GetUserAsync(User);

			var favoriteMovie = new FavoriteMovie
			{
				UserId = user.Id,
				MovieId = movieId
			};

			await _favoriteMovieRepository.AddAsync(favoriteMovie, cancellationToken);

			return RedirectToAction("MoviePage", new { id = movieId });
		}

		/// <summary>
		/// Удаляет фильм из избранного.
		/// </summary>
		/// <param name="movieId">Идентификатор фильма.</param>
		/// <param name="cancellationToken">Токен отмены операции.</param>
		public async Task<IActionResult> RemoveFromFavorites(int movieId, CancellationToken cancellationToken)
		{
			var favoriteMovie = await _favoriteMovieRepository.GetFavoriteMovieAsync(movieId, cancellationToken);

			await _favoriteMovieRepository.DeleteAsync(favoriteMovie, cancellationToken);

			return RedirectToAction("MoviePage", new { id = movieId });
		}
	}
}

Hosts/FilmLens.MVC/Views/Movie/MoviesPage.cshtml
@using FilmLens.Contracts.Movies
<!DOCTYPE html>
<html class="no-js" lang="ru">
@model MoviesListDto

<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge" />
	<meta name="keywords" content="online solution, it, tech, sass, technology, teaching, learning">
	<meta name="description"
		  content="Techy is a it solutions HTML template for all kinds of it, technology, online tech website">
	<title>FilmLens</title>
	<meta property="og:site_name" content="FilmLens">
	<meta property="og:url" content="">
	<meta property="og:type" content="website">
	<meta property="og:title" content="FilmLens – IT Solution & Web Security HTML5 Template">
	<meta name='og:image' content='~/img/ogg.png'>
	<!-- For IE -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- For Resposive Device -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- For Window Tab Color -->
	<!-- Chrome, Firefox OS and Opera -->
	<meta name="theme-color" content="#913BFF">
	<!-- Windows Phone -->
	<meta name="msapplication-navbutton-color" content="#913BFF">
	<!-- iOS Safari -->
	<meta name="apple-mobile-web-app-status-bar-style" content="#913BFF">

	<!-- <link rel="manifest" href="site.webmanifest" /> -->
	<link rel="shortcut icon" type="image/x-icon" href="~/img/favicon.png" />
	<!-- Place favicon.ico in the root directory -->
	<!-- CSS here -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/fonts/custom-font/css/clash-display.css" />
	<link rel="stylesheet" href="~/fonts/bootstrap-icons/font-css.css" />
	<link rel="stylesheet" href="~/css/slick.css" />
	<link rel="stylesheet" href="~/css/all.min.css" />
	<link rel="stylesheet" href="~/css/metisMenu.css" />
	<link rel="stylesheet" href="~/css/aos.css" />
	<link rel="stylesheet" href="~/css/spacing.css" />
	<link rel="stylesheet" href="~/css/main.css" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>

<body>
	<div class="main-page-wrapper">
		<!-- preloader -->
		<div id="preloader">
			<div class="preloader">
				<span></span>
				<span></span>
			</div>
		</div>
		<!-- preloader end  -->
		<!-- offcanvas start  -->
		<div class="offcanvas offcanvas-top theme-bg" tabindex="-1" id="offcanvasTop">
			<div class="offcanvas-header">
				<a data-bs-dismiss="offcanvas" aria-label="Close">
					<i class="fas fa-times search-close" id="search-close"></i>
				</a>
			</div>
			<div class="offcanvas-body">
				<!-- Fullscreen search -->
				<div class="search-wrap">
					<form method="get">
						<input type="search" class="main-search-input" placeholder="Search Your Keyword...">
					</form>
				</div>
				<!-- end fullscreen search -->
			</div>
		</div>
		<!-- offcanvas end  -->
		<!-- header-area start -->
		<header class="theme-main-menu py-lg-4">
			<div class="main-header-area">
				<div class="container custom-container-nav">
					<div class="row gx-4 gx-xxl-5 align-items-center">
						<div class="col-xxl-3 col-xl-2 col-lg-2 col-6 text-start">
							<div class="logo-area">
								<a href="@Url.Action("Index", "Home")"><img src="~/img/logo/FilmLensLogo.png" alt="Header-logo"></a>
							</div>
						</div>
						<div class="col-xxl-6 col-xl-6 col-lg-6 d-none d-lg-block">
							<nav class="navbar navbar-expand-lg">
								<div class="container-fluid">
									<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
											data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
											aria-expanded="false" aria-label="Toggle navigation">
										<span class="navbar-toggler-icon"></span>
									</button>
									<div class="collapse navbar-collapse" id="navbarSupportedContent">
										<ul class="navbar-nav mb-2 mb-lg-0 ps-1 justify-content-center">

											<li class="nav-item dropdown">
												<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownOne"
												   role="button" data-bs-toggle="dropdown" aria-expanded="false">
													Каталог
												</a>
												<ul class="dropdown-menu" aria-labelledby="navbarDropdownOne">
													<li><a class="dropdown-item" asp-controller="Movie" asp-action="MoviesPage"><i class="fas fa-film"></i> Фильмы</a></li>
												</ul>
											</li>

											<li class="nav-item">
												<a class="nav-link" asp-controller="Genre" asp-action="GenresPage">Жанры</a>
											</li>

											@if (User?.Identity?.IsAuthenticated == true)
											{
												<li class="nav-item">
													<a class="nav-link" asp-controller="User" asp-action="Profile">Профиль</a>
												</li>
											}

										</ul>
									</div>
								</div>
							</nav>
						</div>
						<div class="col-xxl-3 col-xl-4 col-lg-4 col-6 text-end">
							<ul class="right-nav mb-0 d-flex align-items-center justify-content-end">
								<li>
									<div class="d-none d-xxl-inline-block right-language pr-40">
									</div>
								</li>
								<li class="search-area">
									<a class="search_input" href="#" data-bs-toggle="offcanvas"
									   data-bs-target="#offcanvasTop" aria-controls="offcanvasTop">
										<i class="bi bi-search"></i>
									</a>
								</li>
								<li>
									<div class="hamburger-menu">
										<a class="round-menu" href="javascript:void(0);">
											<i class="bi bi-list"></i>
										</a>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</header>
		<!-- header-area end -->
		<!-- slide-bar start -->
		<aside class="slide-bar">
			<div class="close-mobile-menu">
				<a href="javascript:void(0);">
					<i class="fas fa-times"></i>
				</a>
			</div>
			<!-- offset-sidebar start -->
			<div class="offset-sidebar">
				<div class="offset-widget offset-logo mb-30">
					<a href="index.cshtml">
						<img src="~/img/logo/FilmLensLogo2.png" alt="logo">
					</a>
				</div>
				<div class="offset-widget mb-40">
					<div class="info-widget">
						<h4 class="offset-title mb-20">О нас</h4>
						<p class="mb-30">
							FilmLens — это твой личный кинокритик и проводник в мир кинематографа. Наша платформа
							создана для того, чтобы ты мог легко и быстро находить фильмы для любого случая — будь то
							вечер в кругу друзей или уютный просмотр дома.
						</p>
					</div>
				</div>
				<div class="offset-widget mb-30 pr-10">
					<div class="info-widget info-widget2">
						<h4 class="offset-title mb-20">Контактная информация</h4>
						<p>
							<i class="fal fa-envelope-open"></i>
							support@filmlens.com
						</p>
					</div>
				</div>

				@if (User?.Identity?.IsAuthenticated == true)
				{
					<div class="login-btn text-center">
						<a class="theme_btn w-100" asp-controller="Account" asp-action="Logout">Выйти</a>
					</div>
				}
				else
				{
					<div class="login-btn text-center">
						<a class="theme_btn w-100" asp-controller="Account" asp-action="Login">Войти</a>
					</div>
					<div class="login-btn text-center">
						<a class="theme_btn w-100" asp-controller="Account" asp-action="Register">Зарегистрироваться</a>
					</div>
				}

			</div>
			<!-- offset-sidebar end -->

		</aside>
		<div class="body-overlay"></div>
		<!-- slide-bar end -->

		<main>
			<!--our-services start-->
			<section class="latest-case-work pt-70 pb-150 pt-lg-60 pb-lg-120">
				<div class="container">
					<div class="row gx-4 gx-xxl-5 align-items-center justify-content-center">
						<div class="col-xl-5 col-lg-6 col-md-8">
							<div class="section-title text-center mb-55">
								<h3 class="sect-title mb-25" data-aos="fade-up">Фильмы</h3>
								<p data-aos="fade-up" data-aos-delay="100">
									@Model.GenreName
								</p>
							</div>
						</div>
					</div>
					@if (Model.Result.Count() == 0)
					{
						<div class="row gx-4 gx-xxl-5 align-items-center justify-content-center">
							<div class="col-xl-5 col-lg-6 col-md-8">
								<div class="section-title text-center mb-90">
									<h3 class="sect-title mt-100 mb-25" data-aos="fade-up">В избранном пусто</h3>
								</div>
							</div>
						</div>
					}
					<div class="row gx-4 gx-xxl-5">

						

						@foreach (var movie in Model.Result)
						{
							<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
								<div class="team-style-two text-center mb-45">
									<div class="team-thumb">
										<a href="@Url.Action("MoviePage", new {id = movie.Id})">
											<img src="https://image.tmdb.org/t/p/w500@(movie.PosterUrl)"
																		 alt="@movie.Title" 
																		 style="width: 370px; height: 513px; object-fit: cover;"
																		 class="img-fluid">
										</a>
									</div>
									<div class="team-content">
										<h3 class="sect-title-two"><a href="@Url.Action("MoviePage", new {id = movie.Id})">@movie.Title</a></h3>
									</div>
								</div>
							</div>
						}
	
						<nav aria-label="Page navigation example">
							<ul class="pagination justify-content-center">
								@if (Model.PageNumber > 1)
								{
									<li class="page-item">
										<a class="page-link" href="@Url.Action("MoviesPage", new { pageNumber = Model.PageNumber - 1, 
																								   genreId = Model.GenreId,
																								   userId = Model.UserId,
																								   genreName = Model.GenreName })">Назад</a>
									</li>
								}

								<!-- Показ нескольких номеров страниц -->
								@{
									var pagesCount = Math.Ceiling((decimal)Model.TotalCount / Model.PageSize);
								}
								@for (var i = 1; i <= pagesCount; i++)
								{
									if (i == Model.PageNumber)
									{
										<li class="page-item active">
											<span class="page-link">@i</span>
										</li>
									}
									else if (i <= 3 || i == Model.TotalCount || (i >= Model.PageNumber - 2 && i <= Model.PageNumber + 2))
									{
										<li class="page-item">
											<a class="page-link" href="@Url.Action("MoviesPage", new { pageNumber = i, 
																									   genreId = Model.GenreId,
																									   userId = Model.UserId,
																									   genreName = Model.GenreName })">@i</a>
										</li>
									}
									else if (i == 4)
									{
										<li class="page-item">
											<span class="page-link">...</span>
										</li>
									}
									else if (i == pagesCount)
									{
										<li class="page-item">
											<a class="page-link" href="@Url.Action("MoviesPage", new { pageNumber = i, 
																									   genreId = Model.GenreId, 
																									   userId = Model.UserId,
																									   genreName = Model.GenreName })">@i</a>
										</li>
									}
								}

								@if (Model.PageNumber < pagesCount)
								{
									<li class="page-item">
										<a class="page-link" href="@Url.Action("MoviesPage", new { pageNumber = Model.PageNumber + 1, 
																								   genreId = Model.GenreId, 
																								   userId = Model.UserId,
																								   genreName = Model.GenreName })">Вперед</a>
									</li>
								}
							</ul>
						</nav>

					</div>
				</div>
			</section>
			<!--our-services end-->
		</main>
	</div>

	<!-- JS here -->

	<script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
	<script src="~/js/vendor/jquery-2.2.4.min.js"></script>
	<script src="~/js/vendor/popper.min.js"></script>
	<script src="~/js/vendor/bootstrap.min.js"></script>
	<script src="~/js/slick.min.js"></script>
	<script src="~/js/jquery.supermarquee.min.js"></script>
	<script src="~/js/imagesloaded.pkgd.min.js"></script>
	<script src="~/js/isotope.pkgd.min.js"></script>
	<script src="~/js/jquery.magnific-popup.min.js"></script>
	<script src="~/js/metisMenu.min.js"></script>
	<script src="~/js/wow.min.js"></script>
	<script src="~/js/aos.js"></script>
	<script src="~/js/jquery.counterup.min.js"></script>
	<script src="~/js/jquery.waypoints.min.js"></script>
	<script src="~/js/tilt.jquery.min.js"></script>
	<script src="~/js/jquery.easypiechart.min.js"></script>
	<script src="~/js/jquery-ui.js"></script>
	<script src="~/js/jquery.scrollUp.min.js"></script>
	<script src="~/js/plugins.js"></script>

	<!--Custom JS here -->
	<script src="~/js/main.js"></script>

</body>

</html>